kind: pipeline
name: default
type: kubernetes

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.registry.svc.cluster.local
    repo: registry.registry.svc.cluster.local/comed-exporter
    insecure: true
    auto_tag: true
